"""empty message

Revision ID: 459685bf1515
Revises: bb3a4037eadf
Create Date: 2020-02-14 09:57:24.811394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459685bf1515'
down_revision = 'bb3a4037eadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birthday_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birthday_year', sa.Integer(), nullable=True))
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('users', 'birthday_year')
    op.drop_column('users', 'birthday_month')
    op.drop_column('users', 'birthday_day')
    # ### end Alembic commands ###
