"""empty message

Revision ID: bb3a4037eadf
Revises: 23e8a6393e62
Create Date: 2020-02-13 23:57:32.718568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3a4037eadf'
down_revision = '23e8a6393e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('post_card_id', sa.String(length=256), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('send_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_cards')
    # ### end Alembic commands ###
