"""empty message

Revision ID: c943a4c11b15
Revises: 36188ef8d172
Create Date: 2020-02-13 22:41:36.449465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c943a4c11b15'
down_revision = '36188ef8d172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_line_1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_line_2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_zip_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address_zip_code')
    op.drop_column('users', 'address_state')
    op.drop_column('users', 'address_line_2')
    op.drop_column('users', 'address_line_1')
    op.drop_column('users', 'address_country')
    op.drop_column('users', 'address_city')
    # ### end Alembic commands ###
